version: 0.2

phases:
  install:
    runtime-versions:
       java: corretto17
  pre_build:
    commands:
       - echo Logging in to Amazon ECR...
       - aws --version
       - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 860061945305.dkr.ecr.us-west-2.amazonaws.com
       - IMAGE_NAME=library-eureka-server
       - IMAGE_URI=860061945305.dkr.ecr.us-west-2.amazonaws.com/library-eureka-server:latest
       - CONTAINER_NAME=practice-jpa
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd eureka-server
      - mvn clean package
      - echo Building the docker image
      - docker build -t eureka-server .
      - docker tag eureka-server 941516478045.dkr.ecr.$AWS_REGION.amazonaws.com/pod4-service-registry:eureka-server
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 941516478045.dkr.ecr.$AWS_REGION.amazonaws.com/pod4-service-registry:eureka-server
      - echo Writing definition files
      - printf '[{"name":"ij028-pod4-eureka-server-container","imageUri":"%s"}]' 941516478045.dkr.ecr.$AWS_REGION.amazonaws.com/pod4-service-registry:eureka-server > taskdefinition.json

artifacts:
  files: eureka-server/taskdefinition.json